bootstrap:
  - name: cloudera-bootstrap
    box: centos/7
    hostname: cloudera-bootstrap
    ip: 192.168.25.170
    memory: 4096
    cpu: 4
    disk: 20GB
  
servers:  
  - name: cloudrea1.network.com
    box: centos/7
    hostname: cloudrea1.network.com
    ip: 192.168.25.171
    memory: 16384
    cpu: 4
    disk: 50GB
  
  - name: cloudrea2.network.com
    box: centos/7
    hostname: cloudrea2.network.com
    ip: 192.168.25.172
    memory: 16384
    cpu: 4
    disk: 50GB
  
  - name: cloudrea3.network.com
    box: centos/7
    hostname: cloudrea3.network.com
    ip: 192.168.25.173
    memory: 16384
    cpu: 4
    disk: 50GB
  
numberOfservers: 3